# Generated by Django 5.0 on 2024-01-03 02:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0002_commande"),
    ]

    operations = [
        migrations.RenameField(
            model_name="commande",
            old_name="addresse",
            new_name="address",
        ),
    ]
