# Generated by Django 5.0 on 2024-01-03 04:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0003_rename_addresse_commande_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="commande",
            name="total",
            field=models.CharField(default="500", max_length=200),
            preserve_default=False,
        ),
    ]
